### Support Vector Machine ### 
library(readxl) # importing xls & xlsx files
library(dplyr) # used for nesting/chaining
library(tidyr) # data cleaning
library(stringr) # Used to detect OT and Shootouts
library(writexl) # exporting to xlsx file
library(chron) # Date conversion to Time
library(stats) # Group Functional
library(plyr) # ddpylr for aggregation
library(caret) # Confusion Matrix
library(gmodels) #cross table
library(ggplot2)
library(cowplot)
library(tidyverse)
library(broom)
library(kernlab) #used for SVM
library(neuralnet) #used for ANN
library(e1071)

# Set up Directories

getwd()

setwd("C:/Users/David/Documents/MSDS 696/data")

# Import Data
dtrain = read_excel("Training Final CM.xlsx", col_names = TRUE)
dtest = read_excel("Test Final CM.xlsx", col_names = TRUE)

ttrain = read_excel("Training Final.xlsx", col_names = TRUE)
ttest = read_excel("Test Final.xlsx", col_names = TRUE)

# Remove results from test set
test = dtest[,-4]
atest = ttest[,-4]

# Remove Team Names and Data from training and test sets
dtrain = dtrain[, -c(1:3, 37,38)] #dont need games played with cm
ttrain = ttrain[, -c(1:3, 37,38)]
dtest = dtest[, -c(1:3, 37,38)]
ttest = ttest[, -c(1:3, 37,38)]

# Convert data to factors
dtrain$Result = as.factor(dtrain$Result)

dtest$Result = as.factor(dtest$Result)

dt = rbind(dtrain, dtest)

attach(dtrain)

# Support Vector Machine - test on goals
#rbf got 55.5, laplacedot got 55.2 
svm_model = ksvm(Result ~ Home_Goals + Away_Goals, data = dtrain, cost = 0.5)

pred = predict(svm_model, test)

results = table(dtest$Result, pred)

results

recal = results[4]/(results[4] + results[2])
prec = results[4]/(results[4] + results[3])

acc = (results[1] + results[4])/nrow(dtest)

recal
prec
acc

# SVM Full model
svm_model = ksvm(Result ~ ., data = dtrain)

pred = predict(svm_model, test)

results = table(dtest$Result, pred)

results

recal = results[4]/(results[4] + results[2])
prec = results[4]/(results[4] + results[3])

acc = (results[1] + results[4])/nrow(dtest)

recal
prec
acc

# verify results
agreement = pred == dtest$Result
table(agreement)

prop.table(table(agreement))

# best model? 57.48
svm_model = ksvm(Result ~ Home_Goals + Away_Goals + Home_Shots + Away_Shots + Home_Corsi + Away_Corsi + Home_Corsi_A + Away_Corsi_A + Home_SA + Away_SA + Home_PIM_A + Away_PIM_A, data = dtrain, cost = 0.1, kpar=list(sigma=0.1))

pred = predict(svm_model, test)

results = table(dtest$Result, pred)


results

recal = results[4]/(results[4] + results[2])
prec = results[4]/(results[4] + results[3])

acc = (results[1] + results[4])/nrow(dtest)

recal
prec
acc

confusionMatrix(table(pred, dtest$Result), positive = "W")


# potential plot? use svm
svm_model = svm(Result ~ Home_Goals + Away_Goals + Home_Shots + Away_Shots + Home_Corsi + Away_Corsi + Home_Corsi_A + Away_Corsi_A + Home_SA + Away_SA + Home_PIM_A + Away_PIM_A, data = dtrain)
plot(svm_model, dtrain[,c(1,2,3,6,7,8,9,20,21,22,23)])


svm_model = svm(Result ~ Home_Goals + Away_Goals, data = dtrain)
plot(svm_model, dtrain[,c(1:3)])

plot(svm_model, data = dtrain)

# use ksvm
w = colSums(coef(svm_model)[[1]] * dtrain[alphaindex(svm_model)[[1]], c("Home_Goals", "Away_Goals")])

b = b(svm_model)

ggplot(dtrain, aes(Home_Goals, Away_Goals, color = Result)) + geom_point(size = 2) + geom_abline(intercept = b/w[1], slope = -w[2]/w[1]) + geom_abline(intercept = (b+1)/w[1], slope = -w[2]/w[1], linetype = 2)

# tune model # 13 minutes>????
set.seed(18)

tmodel = tune(svm, Result ~ Home_Goals + Away_Goals, data = dtrain, ranges = list(epsilson = seq(0,1,0.1), cost = 2^(5:8)))

plot(tmodel)

summary(tmodel) #cost for 256 performed best, 0 ep

svm_model = tmodel$best.model

# why not - cross validation

fitControl = trainControl(method = "cv", number = 5, search = 'random', savePredictions = T)

modelfitsvm = train(Result ~ Home_Goals + Away_Goals + Home_Shots + Away_Shots + Home_Corsi + Away_Corsi + Home_Corsi_A + Away_Corsi_A + Home_SA + Away_SA + Home_PIM_A + Away_PIM_A, data = dtrain, method = "svmRadialSigma", trControl = fitControl, tuneLength = 20)

modelfitsvm
modelfitsvm$bestTune

sub_svm = subset(modelfitsvm$pred, (modelfitsvm$pred$C==modelfitsvm$bestTune$C) & modelfitsvm$pred$sigma==modelfitsvm$bestTune$sigma)

confusionMatrix(table(sub_svm$pred, sub_svm$obs))